---
development:
  dialect: mysql
  database: macrobuffalo
  user: root
  password: 123456
  host: 192.168.47.140
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/xiao_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/xiao_production?sslmode=disable"}}
