version: '3'

services:
  buffalo:
    image: mybuffalo:latest
    build: .
    container_name: MyBuffalo
    depends_on:
      - postgresdb
    #command: sh -c "go run ."
    #environment:
    #  - PORT=5000
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - /root/colin_data/api:/go/src/github.com/authrecipe
  postgresdb:
    image: postgres
    container_name: MyPostgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-storage:/var/lib/postgresql/data
volumes:
  postgres-storage: